export const SUPPORTED_LANGUAGES = [
  { code: 'hi', label: 'हिंदी', englishLabel: 'Hindi' },
  { code: 'en', label: 'English', englishLabel: 'English' },
  { code: 'ta', label: 'தமிழ்', englishLabel: 'Tamil' },
  { code: 'te', label: 'తెలుగు', englishLabel: 'Telugu' },
  { code: 'mr', label: 'मराठी', englishLabel: 'Marathi' },
  { code: 'bn', label: 'বাংলা', englishLabel: 'Bengali' },
  { code: 'kn', label: 'ಕನ್ನಡ', englishLabel: 'Kannada' },
  { code: 'gu', label: 'ગુજરાતી', englishLabel: 'Gujarati' },
];

const strings = {
  hi: {
    // Onboarding
    welcome:            'LPG Track में आपका स्वागत है',
    welcomeSubtitle:    'अपना गैस ट्रैक करें, सही समय पर बुक करें',
    selectLanguage:     'अपनी भाषा चुनें',
    familySize:         'घर में कितने लोग हैं?',
    cookingStyle:       'आप कैसे खाना बनाती हैं?',
    cookingSimple:      'सीधा-सादा',
    cookingModerate:    'सामान्य',
    cookingElaborate:   'पूरा भारतीय खाना',
    getStarted:         'शुरू करें',
    next:               'आगे',
    // Home
    gasRemaining:       'गैस बाकी',
    daysLeft:           'दिन बचे',
    todayLog:           'आज का खाना',
    newCylinder:        'नया सिलेंडर',
    bookNow:            'अभी बुक करें',
    cylinderStarted:    'सिलेंडर शुरू हुआ',
    noActiveCylinder:   'कोई सिलेंडर नहीं',
    tapToStart:         'नया सिलेंडर शुरू करें',
    // Meal logging
    logToday:           'आज का खाना लॉग करें',
    tea:                'चाय',
    breakfast:          'नाश्ता',
    lunch:              'दोपहर का खाना',
    dinner:             'रात का खाना',
    extra:              'अतिरिक्त',
    saveLog:            'सहेजें',
    logSaved:           'लॉग सहेजा गया!',
    // New Cylinder
    startNewCylinder:   'नया सिलेंडर शुरू करें',
    startDate:          'शुरुआत की तारीख',
    cylinderBrand:      'सिलेंडर ब्रांड',
    takePhoto:          'फोटो लें',
    confirm:            'शुरू करें',
    // History
    history:            'इतिहास',
    avgDuration:        'औसत समय',
    days:               'दिन',
    // Settings
    settings:           'सेटिंग्स',
    language:           'भाषा',
    familySizeLabel:    'परिवार का आकार',
    notifications:      'नोटिफिकेशन',
    reminderTime:       'याद दिलाने का समय',
    testNotification:   'टेस्ट नोटिफिकेशन',
    saveSettings:       'सहेजें',
    // Urgency messages
    safe:               'गैस ठीक है',
    low:                'गैस कम हो रही है — बुक करें',
    critical:           'गैस लगभग खत्म! अभी बुक करें',
    // Voice
    voiceHint:          'बोलें: "आज चाय और नाश्ता बनाया"',
    listening:          'सुन रही हूँ...',
  },

  en: {
    welcome:            'Welcome to LPG Track',
    welcomeSubtitle:    'Track your gas, book on time',
    selectLanguage:     'Choose your language',
    familySize:         'How many people in your home?',
    cookingStyle:       'How do you cook?',
    cookingSimple:      'Simple cooking',
    cookingModerate:    'Moderate cooking',
    cookingElaborate:   'Elaborate Indian cooking',
    getStarted:         'Get Started',
    next:               'Next',
    gasRemaining:       'Gas Remaining',
    daysLeft:           'Days Left',
    todayLog:           "Today's Cooking",
    newCylinder:        'New Cylinder',
    bookNow:            'Book Now',
    cylinderStarted:    'Cylinder started',
    noActiveCylinder:   'No active cylinder',
    tapToStart:         'Start a new cylinder',
    logToday:           "Log today's cooking",
    tea:                'Tea',
    breakfast:          'Breakfast',
    lunch:              'Lunch',
    dinner:             'Dinner',
    extra:              'Extra',
    saveLog:            'Save',
    logSaved:           'Log saved!',
    startNewCylinder:   'Start New Cylinder',
    startDate:          'Start Date',
    cylinderBrand:      'Cylinder Brand',
    takePhoto:          'Take Photo',
    confirm:            'Start Cylinder',
    history:            'History',
    avgDuration:        'Average Duration',
    days:               'days',
    settings:           'Settings',
    language:           'Language',
    familySizeLabel:    'Family Size',
    notifications:      'Notifications',
    reminderTime:       'Reminder Time',
    testNotification:   'Test Notification',
    saveSettings:       'Save Settings',
    safe:               'Gas level is good',
    low:                'Gas is running low — book soon',
    critical:           'Gas almost empty! Book now',
    voiceHint:          'Say: "I made tea and breakfast today"',
    listening:          'Listening...',
  },
};

// For unsupported languages, fall back to Hindi
export function getStrings(langCode) {
  return strings[langCode] || strings['hi'];
}

export default strings;
